# Generated by Django 5.0.6 on 2024-06-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_booking_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id2',
        ),
    ]
